### ISSUE TITLE
más referencias interesantes

### ISSUE THREAD

**Issue by Julenasti** [DatSciR/intro_prog_fun#3]
https://epiverse-trace.github.io/posts/for-vs-apply/

**Comment by VeruGHub** [comment]
https://ivelasq.rbind.io/blog/understanding-the-r-pipe/

**Comment by Julenasti** [comment]
https://emf.creaf.cat/workflows/r_parallel_computing_tech_doc/

**Comment by Julenasti** [comment]
https://jennybc.github.io/purrr-tutorial/index.html

**Comment by Julenasti** [comment]
https://cran.r-project.org/web/packages/dplyr/vignettes/programming.html

el data masking y el tidy selection son dos problemas muy comunes al que uno se enfrenta cuando empieza a escribir funciones en formato tidy. Creo que por lo menos añadir el link estaría bien

**Comment by Julenasti** [comment]
quizás en un link podríamos poner más variantes de map que no profundizamos pero que pueden ser útiles
https://adv-r.hadley.nz/functionals.html#map-variants

**Comment by Julenasti** [comment]
esta reflexión también me parece interesante:
_The more clearly you can express the intent of your code through function names, the more easily others (including future you!) can read and understand the code._
https://adv-r.hadley.nz/function-operators.html

**Comment by Julenasti** [comment]
creo que podriamos ampliar la parte de programación orientada a objetos (OOP) para que quede un poco más claro la diferencia con FP. Aquí alguna información relativamente sencilla de entender que nos puede ayudar en esto: 
Generally in R, functional programming is much more important than object-oriented programming, because you typically solve complex problems by decomposing them into simple functions, not simple objects. 
https://adv-r.hadley.nz/oo.html
sigo
