### ISSUE TITLE
mejoras

### ISSUE THREAD

**Issue by Julenasti** [DatSciR/intro_prog_fun#4]
creo que este ejemplo se podría actualizar utilizando el nuevo shortcut the purrr \(x) DONE
https://github.com/Julenasti/intro_prog_fun/blob/fd886c0fb9862b0a50cbe1b88255a9c6c71d0a5a/intro_prog_fun.qmd#L221 

creo que aquí se lo podría dar un nombre más explicativo a la función DONE
https://github.com/Julenasti/intro_prog_fun/blob/1dce3c43699c104d78fb6026818d5e36abb44156/intro_prog_fun.qmd#L353

**Comment by Julenasti** [comment]
- añadir ejercicios @Julenasti @VeruGHub 
- ampliar la parte de programación en r en la intro @VeruGHub 
- añadir parellel computing @Julenasti 
- funciones en tidyverse @VeruGHub 
- revisar los demás enlaces y decidir qué incluir @Julenasti @VeruGHub 
- traducir al inglés

**Comment by Julenasti** [comment]
@VeruGHub he revisado tus updates. Yo creo que está genial!! Te he añadido unas cuantas sugerencias. Busca la palabra julen para encontrarlas. Gracias!!
https://github.com/Julenasti/intro_prog_fun/commit/180c242e9d11d96422466db9ee208a575d00880e

**Comment by VeruGHub** [comment]
He simplificado el apartado de cómo escribir una función, quitando la parte de if else. Creo que para este curso era demasiado complejo. Ya me dirás que te parece si te da tiempo para el miercoles

**Comment by VeruGHub** [comment]
- Añadir una encuesta de satisfacción al final?

**Comment by Julenasti** [comment]
@VeruGHub intentaría enviarles los apuntes un poco antes del jueves que viene aunque luego cambiemos alguna cosilla para que puedan por lo menos leer una vez los apuntes antes de iniciar el curso porque en el último curso una sugerencia fue justo esta. Principalmente en mi parte que hay bastante teoría. Qué te parece?

**Comment by VeruGHub** [comment]
Okis, gracias por la info. Sólo decía que se mencionara porque en R base se usa porque no todo es tan tidy y por si alguien lo necesita.
No me salen las imágenes que has subido tu en la carpeta de imagenes. A ti te salen las mias?
He incluido ya mi parte. He quitado la parte de programación en R base pero he dejado la programación básica de tidyverse. Si vemos que ya saben tidyverse me lo puedo saltar. También he revisados tus comentarios. 
Me parece bien enviarles los apuntes antes. 
Para comentar:
- Compeltar entre los dos la parte de la estructura del curso.
- Yo reduciría la parte de programación orientada a objetos, creo que lia más que aclara y no se necesita para entender.

**Comment by Julenasti** [comment]
he hecho revisión general y subido a github. No tengo ningún comenatario más de tu parte. Por mi parte ya estaría!
